//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiznikHealthForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESSLEVEL
    {
        public int AccessID { get; set; }
        public int Access_Level { get; set; }
        public string Access_Area { get; set; }
        public string Description { get; set; }
    }
}
