//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiznikHealthForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int CompanyID { get; set; }
        public string Company_Name { get; set; }
        public string Description { get; set; }
    }
}
