//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiznikHealthForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_INITIATION
    {
        public int EmpID { get; set; }
        public string Full_Name { get; set; }
        public string Job_Role { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Start_Date { get; set; }
        public string Job_Others { get; set; }
        public string Services_Equipment { get; set; }
        public string Services_Equipment_Others { get; set; }
        public string Additional_Services { get; set; }
        public int Work_For { get; set; }
        public string Work_For_Others { get; set; }
        public string Work_For_Additional_Info { get; set; }
        public string Access_Level1 { get; set; }
        public string Access_Level1_Other { get; set; }
        public string Access_Level1_Restriction { get; set; }
        public string Access_Level2 { get; set; }
        public string Access_Level2_Other { get; set; }
        public string Access_Level2_Restriction { get; set; }
        public string Access_Level3 { get; set; }
        public string Access_Level3_Other { get; set; }
        public string Today_Date { get; set; }
        public int Hiring_Manager_ID { get; set; }
        public string Created_Date { get; set; }
        public string Updated_By { get; set; }
        public string Updated_Date { get; set; }
        public bool Status { get; set; }
    }
}
