//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiznikHealthForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class niznik_dbEntities : DbContext
    {
        public niznik_dbEntities()
            : base("name=niznik_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESSLEVEL> ACCESSLEVELs { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<HIRINGMANAGER> HIRINGMANAGERs { get; set; }
        public virtual DbSet<JOB_ROLE> JOB_ROLE { get; set; }
        public virtual DbSet<SERVICES_EQUIPMENT> SERVICES_EQUIPMENT { get; set; }
        public virtual DbSet<COMPANY_ACCESSLEVEL> COMPANY_ACCESSLEVEL { get; set; }
        public virtual DbSet<EMPLOYEE_INITIATION> EMPLOYEE_INITIATION { get; set; }
    }
}
