//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiznikHealthForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIRINGMANAGER
    {
        public int Hiring_ManagerID { get; set; }
        public string Hiring_Manager_Name { get; set; }
        public string Hiring_Manager_Email { get; set; }
    }
}
